language: elixir
elixir:
  - 1.3.3
otp_release:
  - 18.2.1
env:
  global:
    - MIX_ENV=test
before_script:
  - rvm install ruby-2.3.1
  - gem install pronto-credo
script:
  - pronto run -f github_pr
  - mix test --exclude skip
addons:
  postgresql: 9.4
cache:
 directories:
   — /home/travis/.rvm/
